name: naen-tech
static_sites:
- name: web
  github:
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: dist
  catchall_document: index.html
  routes:
  - path: /
  - path: /assets
  - path: /*
    catchall_document: index.html