name: naen-tech
services:
  - name: web
    dockerfile_path: Dockerfile
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /
      port: 80
    http_port: 80
    routes:
      - path: /