name: naen-tech
static_sites:
- name: web
  environment_slug: html
  github:
    repo: naenmad/naen-tech
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: dist
  error_document: index.html
  index_document: index.html
  catchall_document: index.html